[package]
name = "macro_expand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_amqp = { path = "../../serde_amqp", features = ["derive"] }
